### ISSUE TITLE
Error during `upgrade apply` with kubernetes-only upgrade

### ISSUE THREAD

**Issue by derpsteb** [edgelesssys/constellation#1631]
### Issue description

When running `upgrade apply` the follow error message is shown: `Error: upgrading NodeVersion: expected NodeVersion to contain /CommunityGalleries/ConstellationCVM-728bd310-e898-4450-a1ed-21cf2fb0d735/Images/main-nightly/Versions/2023.0406.182050, got /communityGalleries/ConstellationCVM-b3782fa0-0df7-4f2f-963e-fc7fc42663df/images/constellation/versions/2.6.0`

### To reproduce
Any config that will trigger a Kubernetes upgrade, but no image upgrade will print the above error. An example could be:

1. Setup a Constellation cluster with Constellation CLI `v2.6.0` and Kubernetes version `v1.25.7`
2. Change configured Kubernetes version to `v1.26.2`
3. Change configured image version to `/CommunityGalleries/ConstellationCVM-728bd310-e898-4450-a1ed-21cf2fb0d735/Images/main-nightly/Versions/2023.0406.182050`
4. Run `upgrade apply`

### Expected behavior

This error is not shown. 

### Mitigation
The error message itself is harmless. It does not necessarily indicate that the upgrade failed. To check if the upgrade succeeded run `constellation status` and compare the reported values with your local config.
The error is fixed in #1630.

**Comment by thomasten** [comment]
fixed in v2.7.1
