### ISSUE TITLE
Support new AWS image region: eu-west-1

### ISSUE THREAD

**Issue by patlachance** [edgelesssys/constellation#1715]
### Use case
According to the [doc](https://github.com/edgelesssys/constellation/blob/main/docs/versioned_docs/version-2.7/getting-started/first-steps.md?plain=1#L58), Constellation OS images are not available in region eu-west-1. Could you please make it available?

### Describe your solution
Make Constellation images available in region eu-west-1

### Additional context
Need to deploy in this region

**Comment by malt3** [comment]
The image for version v2.7.0 has been replicated to eu-west-1.
Is this the version of Constellation you are currently testing? If there are older versions or regions of interest, please let us know.
 If you have any further questions or require additional support, do not hesitate to contact us again.

**Comment by patlachance** [comment]
Thanks, I'm interested in testing the latest image only.
