### ISSUE TITLE
Support new AWS image region: eu-west-3

### ISSUE THREAD

**Issue by patlachance** [edgelesssys/constellation#1716]
### Use case
According to the [doc](https://github.com/edgelesssys/constellation/blob/main/docs/versioned_docs/version-2.7/getting-started/first-steps.md?plain=1#L58), Constellation OS images are not available in region eu-west-3. Could you please make it available?

### Describe your solution
Make Constellation images available in region eu-west-3

### Additional context
Need to deploy in this region

**Comment by malt3** [comment]
The image for version v2.7.0 has been replicated to eu-west-3. If you have any further questions or require additional support, please do not hesitate to contact us again.

**Comment by patlachance** [comment]
Thanks for the processing delay!
