### ISSUE TITLE
Support cluster upgrade on aws

### ISSUE THREAD

**Issue by patlachance** [edgelesssys/constellation#1717]
### Use case
According to the [doc](https://github.com/edgelesssys/constellation/blob/main/docs/versioned_docs/version-2.7/workflows/upgrade.md?plain=1#L11), cluster upgrade is not yet supported on AWS. This is a show-stopper for production usage.

### Describe your solution
Please implement cluster upgrade feature for clusters deployed on aws

### Additional context
Nothing more to mention!

**Comment by m1ghtym0** [comment]
Hi @patlachance,
Thanks for making us aware of this requirement.
With AWS announcing their AMD SEV-SNP offering this week, we're about to unroll a bunch of functionality for Constellation on AWS shortly.
If you would like to discuss your requirements with our roadmap on AWS in more detail, please feel free to contact me directly via me@edgeless.systems.
Thanks!

**Comment by m1ghtym0** [comment]
This was implemented by https://github.com/edgelesssys/constellation/pull/1758
Will be available in v2.8

**Comment by patlachance** [comment]
Awesome, thanks for the quick implementation!

**Comment by m1ghtym0** [comment]
Hey @patlachance, did you have a chance to test this with v2.8?
Did work as expected or did you run into any trouble?
