### ISSUE TITLE
Support confidential storage on aws

### ISSUE THREAD

**Issue by patlachance** [edgelesssys/constellation#1718]
### Use case
According to the [doc](https://github.com/edgelesssys/constellation/blob/main/docs/versioned_docs/version-2.7/workflows/storage.md?plain=1#L44), confidential storage is not yet supported on AWS. This is a show-stopper for production usage.

### Describe your solution
Please implement confidential storage feature for clusters deployed on aws

### Additional context
Nothing more to mention!

**Comment by m1ghtym0** [comment]
Hey @patlachance,
Encrypted storage on AWS is on our short-term roadmap and will be available soon.
I'll keep you updated on this issue here.

**Comment by m1ghtym0** [comment]
Implemented via Constellation's EBS CSI driver: https://github.com/edgelesssys/constellation-aws-ebs-csi-driver
Will be integrated and automatically deployed with Constellation: https://github.com/edgelesssys/constellation/pull/1981

**Comment by derpsteb** [comment]
Included in the latest release [v2.9](https://github.com/edgelesssys/constellation/releases/tag/v2.9.0)
