### ISSUE TITLE
[CLI] Introduce debug flag for more logging

### ISSUE THREAD

**Issue by derpsteb** [edgelesssys/constellation#188]
### Use case
In case of an error during `create`/`init`/`terminate` as much information as possible is helpful. Currently developers have to add debug prints or use a debugger to get more information of what went wrong.

### Describe your solution
Add logging statements / prints that are only called if a dedicated debug flag is set. These logging statements should include information on what actions are performed on which objects. The more information, the better.

You can use [this logger implementation](https://github.com/katexochen/go-tidy-check/blob/main/logger.go) as architecture blueprint.

### Additional context
- Global flags are set here: [cli/cmd/root.go](https://github.com/edgelesssys/constellation/blob/main/cli/cmd/root.go#L41)
- Example for output behind a CLI flag: [cli/internal/cmd/create.go](https://github.com/edgelesssys/constellation/blob/b8d991f84ca1bcbcd172bf4ab8111308bc36eb4e/cli/internal/cmd/create.go#L111-L124)

**Comment by osintalex** [comment]
Cool project! Can I try this issue?

**Comment by daniel-weisse** [comment]
Hi @osintalex 

We scoped out some of the requirements on how we would like this implemented:

We have our own logging package, which is basically just a wrapper for [zap](https://github.com/uber-go/zap).
We use this logging interface for all other applications of Constellation, and would like to also use this for CLI debug logging.
You can find the source code [in our repo](https://github.com/edgelesssys/constellation/blob/main/internal/logger/log.go), and the documentation is available [here](https://pkg.go.dev/github.com/edgelesssys/constellation/v2@v2.2.2/internal/logger).

I made a small sample implementation on how integrating this in the CLI would look like: https://github.com/edgelesssys/constellation/pull/610

The parts where debug logging is probably the most important are the [`create` command](https://github.com/edgelesssys/constellation/blob/main/cli/internal/cmd/create.go) and the [`init` command](https://github.com/edgelesssys/constellation/blob/main/cli/internal/cmd/init.go), but you can start anywhere you like.
Feel free to implement one command at a time, or at whatever pace suits you best, and reach out if you have any questions along the way.

**Comment by osintalex** [comment]
Wow thanks for the extremely clear scoping - really appreciate that.

[I've just had a go at the create command ](https://github.com/edgelesssys/constellation/compare/main...osintalex:constellation:introduce-debug-flag)- could you let me know if that's what you're looking for?

If it's all looking ok then I'll continue on the other commands and before sending in a PR 👍🏻

**Comment by daniel-weisse** [comment]
Looks good so far :+1:

**Comment by osintalex** [comment]
Awesome, thanks for letting me know!

**Comment by katexochen** [comment]
Closed by #809
