### ISSUE TITLE
[CLI] Activity indicator for init command

### ISSUE THREAD

**Issue by derpsteb** [edgelesssys/constellation#189]
### Use case
When interacting with cloud provider APIs there are actions that take multiple minutes. In those cases the user might become uncertain if the program is still working. Some kind of animation, like a spinner, would improve UX.

### Describe your solution
Implement a small animation that shows that the program is still running, while waiting for the `init` response to come back.

Feel free to also implement this for other commands like `create` or `terminate`.
### Additional context
- Lots of ASCII Art Spinner inspiration and example code: https://stackoverflow.com/questions/2685435/cooler-ascii-spinners
- The `init` request is sent here: [cli/internal/cmd/init.go](https://github.com/edgelesssys/constellation/blob/main/cli/internal/cmd/init.go#L128)

**Comment by BaLiKfromUA** [comment]
Hey! I would be happy to solve this issue in the scope of Hactoberfest 2022. Can you assign it to me, and I will send my solution in October?
