### ISSUE TITLE
AWS: `constellation terminate` fails with `DependencyViolation: The vpc '...' has dependencies and cannot be deleted.` when deploying LB service

### ISSUE THREAD

**Issue by derpsteb** [edgelesssys/constellation#2105]
### Issue description

When a K8s service of type `LoadBalancer` is deployed, the cluster cannot terminate cleanly.
When running `constellation terminate`, termination fails with an error like: 
```
Error: deleting EC2 VPC (vpc-...): DependencyViolation: The vpc 'vpc-...' has dependencies and cannot be deleted.
	status code: 400, request id: ...
```

This is due to buggy cleanup code in the currently used AWS Operator. A [fix](https://github.com/edgelesssys/constellation/pull/2090) is in progress and will be part of an upcoming release. 

### Workaround

Delete the load balancer of each service and their security groups manually before calling `constellation terminate`. You might also delete the VPC manually instead of the security groups. If you already ran `terminate`, you may delete the Elastic IP resources that are attached your Constellation cluster. You can correlate the IPs by either looking at the public IP contained in your `constellation-id.yml` or by looking at the Elastic IP ressources conntected to your offending VPC.

### Expected behavior

`constellation terminate` finishes without errors.

**Comment by elchead** [comment]
is fixed with v2.10
