### ISSUE TITLE
Customers should not be able to create clusters with wrong flavors (stackit)

### ISSUE THREAD

**Issue by h3adex** [edgelesssys/constellation#3438]
### Use case

Is it possible to display a warning when a customer is trying to create a constellation cluster using a wrong flavor id? Currently the customer is able to apply any flavor. Because it is not a confidential one the setup process is stuck in connecting state. Prior creating the cluster we should warn the user if he is using any flavor which is not listed in the list of available stackit flavors.

Available confidential flavors in your codebase:
https://github.com/edgelesssys/constellation/blob/50df35438e1c28c05ad3eed6561a5ccbd92b55a5/internal/config/instancetypes/stackit.go#L10

Once stackit is adding new flavors, I'll create PR to add them. But currently this is the correct list. I can also review/test the PR for this feature request. I might also write some Go-Code to implement it, if you give me a hint where to start.

<img width="634" alt="Screenshot 2024-10-17 at 13 20 45" src="https://github.com/user-attachments/assets/b91e1624-ab11-49c3-a8dc-577306570b57">

### Would you be willing to implement this feature?

- [X] Yes, I could contribute this feature.

**Comment by msanft** [comment]
Hey @h3adex,

That's certainly a good addition! If you want to contribute this, you could add a check to the existing [instance type validation code](https://github.com/edgelesssys/constellation/blob/b8c26f5989a21d7d87abbd7653e3992fbd097e8a/internal/config/validation.go#L523). Additionally, we could add a comment in our [Terraform provider example](https://github.com/edgelesssys/constellation/blob/b8c26f5989a21d7d87abbd7653e3992fbd097e8a/terraform-provider-constellation/examples/full/stackit/main.tf#L28), indicating that a confidential instance type needs to be selected.

Thanks a lot!

**Comment by h3adex** [comment]
PR is merged. Closed this issue. TYVM!
