### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by awdemos** [edgelesssys/constellation#3467]
### Use case

I would like to run Constellation on Apple hardware.

### Describe your solution

Apple claims to have some capability for this on Apple Silicon already the Secure Enclave backend just needs to be exposed to the Constellation bootstrap process. https://security.apple.com/blog/private-cloud-compute/ 

### Would you be willing to implement this feature?

- [x] Yes, I could contribute this feature.

**Comment by 3u13r** [comment]
There are multiple issues that prevent us from porting Constellation to Apple Silicon + macOS:

1. There is no support from the Kubernetes project to run a Kubernetes cluster on that platform.
2. Apple's Secure Enclave has many differences to confidential VMs as they are provided by Intel TDX and AMD SNP.


Therefore, it is currently not planned (even if it was possible) to run a Constellation cluster on Apple Silicon. What we _do_ support is macOS/Apple Silicon as a client. For that, see `constellation-darwin-arm64` in the release binaries.

**Comment by awdemos** [comment]
while 1. is probably true, local deployments of k8 are well supported by Rancher etc. 2. If there is interest from anyone else on a solution for the Apple Secure Enclave work I would be happy to contribute.
