### ISSUE TITLE
Command: [constellation version] returns 0.0.0 instead of 2.1.0

### ISSUE THREAD

**Issue by razine-bensari** [edgelesssys/constellation#364]
### Issue description
The latest constellation cli release (2.1.0) has a bug when displaying the version of the constellation binary.

When running `constellation version` the following version is returned: 0.0.0

Refer to screenshot below:
<img width="429" alt="Screen Shot 2022-10-24 at 11 26 09 AM" src="https://user-images.githubusercontent.com/34013446/197564539-a88d5447-edd7-4414-adb6-8b7ea049227c.png">

### To reproduce

1. Download and install latest constellation binary for macOS (intel) (version 2.1.0 at the time of writing this)
2. Execute the following command: `constellation version`
3. Notice how the displayed version on STD out is 0.0.0 instead of 2.1.0

**Comment by katexochen** [comment]
Hi @razine-bensari, thanks for reporting this issue! The bug was noticed after the release and fixed in https://github.com/edgelesssys/constellation/pull/231. The next released CLI will come with the correct version.
