### ISSUE TITLE
local installation cannot find the qemu image to download

### ISSUE THREAD

**Issue by curx** [edgelesssys/constellation#565]
### Issue description
The needed qemu image cannot be downloaded.

### To reproduce

1. use the [local guide](https://docs.edgeless.systems/constellation/getting-started/first-steps-local)
2. Start the installation
    ```..sh
    constellation mini up 
    Downloading image to ./constellation.raw
    Error: preparing config: downloading image to ./constellation.raw: downloading image: 404 Not Found
    ```

### Environment

- `constellation version`: 
    ```..sh
    constellation version
    Version:        2.2.1
    GitCommit:      15b612b4cbf6c92a889a55b995de56947ff321a9
    GitTreeState:   clean
    BuildDate:      2022-11-14T16:32:39Z
    GoVersion:      go1.19.3
    Compiler:       gc
    Platform:       linux/amd64
    ```

### Expected behavior
the local installation should be usable

**Comment by datosh** [comment]
Hey @curx 
Thanks for trying out our latest Constellation so soon 🙂 

The upload of our QEMU image was still in progress. I will make sure things are uploaded in the correct order for our subsequent releases. 

Everything is in place now. Could you have another try?

**Comment by datosh** [comment]
Please hold off on using v2.2.1, @curx .
We have missed updating the PCR[8] value for our QEMU-based deployment. We are currently preparing v2.2.2 to get that fix in ASAP.
